prior:
  _target_: code.architectures.base.DiagonalNormal
  z_dim: ${params.z_dim}
encoder:
  _target_: code.architectures.CelebA.Encoder
  layers: ${params.encoder_layers}
  z_dim: ${params.z_dim}
decoder:
  _target_: code.architectures.CelebA.Decoder
  z_dim: ${params.z_dim}
  layers: ${params.decoder_layers}
  sigma: ${params.sigma}
predictor:
  _target_: code.architectures.CelebA.LandmarkPredictor
  layers: ${params.predictor_layers}
  z_dim: ${params.z_dim}
