Accuracy/Train:
  evaluate_every: ${eval_params.accuracy.every}
  evaluator:
    _target_: examples.evaluation.accuracy.AccuracyEvaluation
    evaluate_on: train
    n_samples: ${eval_params.accuracy.n_samples}
Accuracy/Validation:
  evaluate_every: ${eval_params.accuracy.every}
  evaluator:
    _target_: examples.evaluation.accuracy.AccuracyEvaluation
    evaluate_on: valid
    n_samples: ${eval_params.accuracy.n_samples}