ELBO/Validation:
  evaluate_every: ${eval_params.elbo.every}
  evaluator:
    _target_: code.evaluation.elbo.ELBOEvaluation
    evaluate_on: valid
    n_samples: ${eval_params.elbo.n_samples}
ELBO/Train:
  evaluate_every: ${eval_params.elbo.every}
  evaluator:
    _target_: code.evaluation.elbo.ELBOEvaluation
    evaluate_on: train
    n_samples: ${eval_params.elbo.n_samples}
