Images/Landmarks:
  evaluate_every: ${eval_params.landmarks.every}
  evaluator:
    _target_: code.evaluation.image.ImageLandmarksEvaluation
    evaluate_on: ${eval_params.landmarks.evaluate_on}
    n_pictures: ${eval_params.landmarks.n_pictures}
    sample_images: False
    sample_latents: ${eval_params.landmarks.sample_latents}
    padding: ${eval_params.landmarks.padding}
