accuracy:
  every: 5 minutes
  n_samples: 2048
elbo:
  every: 5 minutes
  n_samples: 2048
samples:
  every: 5 minutes
  n_samples: 10
reconstruction:
  evaluate_on: valid
  every: 5 minutes
  n_samples: 10
  sample_latents: False
landmarks:
  evaluate_on: valid
  every: 5 minutes
  n_pictures: 10
  sample_latents: False